apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  namespace: yolo
  labels:
    app: yolo-backend
  annotations:
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
      - name: backend
        image: mwas121/yolo-backend:1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://yolo-mongo-service:27017/yolomy"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-service
  namespace: yolo
  labels:
    app: yolo-backend
  annotations:
    role: backend
spec:
  selector:
    app: yolo-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP