apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yolo-mongo
  namespace: yolo
  labels:
    app: yolo-mongo
  annotations:
    version: "4.4"
spec:
  serviceName: yolo-mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: yolo-mongo
  template:
    metadata:
      labels:
        app: yolo-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "yolomy"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-mongo-service
  namespace: yolo
  labels:
    app: yolo-mongo
  annotations:
    role: database
spec:
  selector:
    app: yolo-mongo
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
