- name: Install Docker\n  apt:\n    name: docker.io\n    state: present\n    update_cache: yes\n\n- name: Ensure Docker service is running\n  service:\n    name: docker\n    state: started\n    enabled: yes
